pipeline:
  build:
    image: golang
    commands:
      - go build
      - go run main.go
  webhook:
    image: testdroneimage:latest
    url: http://foo.com
    method: post
    body: |
      hello world
  webhook1:
    image: testdroneimage:latest
    url: http://foo.com
    method: post
    body: |
      hello world111111
  webhook2:
    image: testdroneimage:latest
    url: http://foo.com
    method: post
    body: |
      hello world222222
  webhook3:
    image: testdroneimage:latest
    url: http://foo.com
    method: post
    body: |
      hello world333333344444
